### ISSUE TITLE
EPIC: Admins can remove a user from a commons

### ISSUE THREAD

**Issue by sangitakunapuli** [ucsb-cs156/proj-happycows#115]
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

admin

### I can...

remove a user from a commons

### So that...

I can keep gameplay safe and fun

### Discussion

Admins currently do not have the ability to remove a user from a commons for any reason. Admins may need to remove users who are abusing the game, causing trouble in the chat, or students who are no longer participating in the game (for example).

This feature epic has multiple steps - it is recommended to split it up how you see fit (do frontend changes and backend changes in separate pull requests).

### Acceptance Criteria

- [ ] Admins can choose a user from the list of users and remove them from a specific commons.
- [ ] There is a column called 'Edit Commons' with buttons on the Users table that allows admins to view and remove a user from a commons.
- [ ] When admins click this button, they can see a popup with the user's name and a checkbox list of the commons they are part of
- [ ] An admin can check one or more of these commons to remove this user from those commons.
- [ ] When the user clicks 'Done' on the bottom of the popup, the user has been removed from the specified commons
- [ ] On the user side, this user no longer has access to this commons.

### Implementation Todos

Frontend:
- [ ] Modify the users page to show the commons the user has joined
- [ ] Implement an `Edit Commons` column with edit buttons on the Users table
- [ ] List the commons a user is in as a checkbox list
- [ ] Update this list according to actions taken by the admin

Backend:
- [ ] Fetch the list of commons a user is in (look at the Profile page for a hint on how this is implemented)
- [ ] Use the `/api/commons/{commonsId}/users/{userId}` endpoint to remove a user from a commons

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
will not implement
